### ISSUE TITLE
Print debugging info to stderr

### ISSUE THREAD

**Issue by pbsds** [woodruffw/yamlpath#2]
These lines

https://github.com/woodruffw/yamlpath/blob/8dcfae2f795577390248532e7f21804353eb3f0a/yp/src/main.rs#L31-L35

clutter the output with treesitter ast debugging info. Is it possible to move that bit of the output to stderr? Bonus if it could be enabled/disabled with a cli argument

**Comment by woodruffw** [comment]
> clutter the output with treesitter ast debugging info. Is it possible to move that bit of the output to stderr? Bonus if it could be enabled/disabled with a cli argument

Sure, I'd be happy to review a PR that moves these to `stderr`. Keep in mind that `yp` isn't intended as a full-fledged tool -- it's only a tiny demo of a slice of `yamlpath`'s API surface. So flags and other behavioral changes are welcome, but I don't want people to assume that it's a "mature" tool on its own 🙂

**Comment by pbsds** [comment]
Would you then be against/prefer not to package it in linux distributions?

**Comment by woodruffw** [comment]
> Would you then be against/prefer not to package it in linux distributions?

Yeah, I would recommend not packaging `yp` itself! It's just a demo tool, not something people should use in a load-bearing way.
